# Generated by Django 2.2.5 on 2019-09-23 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.SmallIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
